GET http://localhost:8888
content-type: application/json

###

GET http://localhost:8888/monitoring/all
content-type: application/json

###

POST http://localhost:8888/monitoring
content-type: application/json

{
  "type": "alert",
  "body": {
    "project": "alpha-next",
    "env":"production",
    "type": "alert",
    "description": "",
    "tool": "Zabbix",
    "severity": "biggest"
  }
}
